Document: uvavpn
Title: Debian uvavpn Manual
Author: <insert document author here>
Abstract: This manual describes what uvavpn is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/uvavpn/uvavpn.sgml.gz

Format: postscript
Files: /usr/share/doc/uvavpn/uvavpn.ps.gz

Format: text
Files: /usr/share/doc/uvavpn/uvavpn.text.gz

Format: HTML
Index: /usr/share/doc/uvavpn/html/index.html
Files: /usr/share/doc/uvavpn/html/*.html
