Document: uvalatex
Title: Debian uvalatex Manual
Author: <insert document author here>
Abstract: This manual describes what uvalatex is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/uvalatex/uvalatex.sgml.gz

Format: postscript
Files: /usr/share/doc/uvalatex/uvalatex.ps.gz

Format: text
Files: /usr/share/doc/uvalatex/uvalatex.text.gz

Format: HTML
Index: /usr/share/doc/uvalatex/html/index.html
Files: /usr/share/doc/uvalatex/html/*.html
